package mapreduce

import (
	"hash/fnv"
  "fmt"
	"io/ioutil"
	"log"
	"os"
	"bufio"
)

func doMap(
	jobName string, // the name of the MapReduce job
	mapTask int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(filename string, contents string) []KeyValue,
) {
	//
	// doMap manages one map task: it should read one of the input files
	// (inFile), call the user-defined map function (mapF) for that file's
	// contents, and partition mapF's output into nReduce intermediate files.
	//
	// There is one intermediate file per reduce task. The file name
	// includes both the map task number and the reduce task number. Use
	// the filename generated by reduceName(jobName, mapTask, r)
	// as the intermediate file for reduce task r. Call ihash() (see
	// below) on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
	// Your code here (Part I).
	//

	contents, err := ioutil.ReadFile(inFile)
	if err != nil {
		log.Fatal(err)
	}
	stringContent := string(contents)

	fileName := make([]string, nReduce)
	for i := 0; i < nReduce; i++ {
		fileName[i] = reduceName(jobName, mapTask, i)
		file, err := os.Create(fileName[i])
		if err != nil {
			log.Fatal(err)
		}

		file.Close()
	}

	key := mapF(inFile, stringContent)

	for _, eachKey := range key {
		reduce := ihash(eachKey.Key) % nReduce
		fmt.Println(reduce, fileName[reduce])
		file, err := os.OpenFile(fileName[reduce], os.O_APPEND, 0666)
		if err != nil {
			fmt.Println("I am here", err)
			log.Fatal(err)
		}

		writer := bufio.NewWriter(file)
		fmt.Println(writer, eachKey.Key+" "+eachKey.Key + "\n")

		//_, err = file.WriteString(eachKey.Key+" "+eachKey.Key + "\n")
		//if err != nil {
		//	log.Fatal(err)
		//}

		file.Close()
	}

	fmt.Println("HERE I AM ")
	//contents, _ = ioutil.ReadFile(fileName[0])
	//fmt.Println("contents are: ",string(contents))
	return
}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
